# Generated by Django 2.2 on 2019-04-12 20:36

import datetime
from django.db import migrations, models
import pls.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=pls.models.can_path)),
                ('party', models.CharField(default='', max_length=100)),
                ('symbol', models.ImageField(blank=True, null=True, upload_to=pls.models.party_path)),
                ('affitavid', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '2. Facilities',
            },
        ),
        migrations.CreateModel(
            name='pwd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epic', models.CharField(max_length=10)),
                ('phone', models.BigIntegerField(default=0)),
                ('pickupLat', models.FloatField(default=0)),
                ('pickupLon', models.FloatField(default=0)),
                ('pickupTime', models.TimeField(default=datetime.time(16, 0))),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(default='', max_length=100)),
                ('votes', models.IntegerField(default=0)),
                ('party', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=1000)),
                ('rating', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epic', models.CharField(max_length=10)),
                ('phone', models.BigIntegerField(default=0)),
                ('pickupLat', models.FloatField(default=0)),
                ('pickupLon', models.FloatField(default=0)),
                ('pickupTime', models.TimeField(default=datetime.time(16, 0))),
            ],
        ),
        migrations.CreateModel(
            name='pollingStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=100)),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
                ('address', models.CharField(default='', max_length=500)),
                ('no', models.IntegerField(default=0)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=pls.models.user_path)),
                ('fName', models.ManyToManyField(to='pls.facility')),
            ],
            options={
                'verbose_name_plural': '1. Polling Stations',
            },
        ),
    ]
