# Generated by Django 2.2 on 2019-04-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterModelOptions(
            name='pollingstation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pwd',
            options={'verbose_name_plural': '(special voters) Divyangs'},
        ),
        migrations.AlterModelOptions(
            name='thirdgender',
            options={'verbose_name_plural': '(special voters) +66Third Genders'},
        ),
        migrations.AddField(
            model_name='pollingstation',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
