# Generated by Django 2.2 on 2019-04-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pls', '0002_auto_20190413_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thirdgender',
            options={'verbose_name_plural': '(special voters) Third Genders'},
        ),
    ]
