# Generated by Django 2.2 on 2019-04-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pls', '0003_auto_20190413_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingstation',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
