# Generated by Django 2.2 on 2019-04-13 11:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pls', '0004_pollingstation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='pickupPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('pickupLat', models.FloatField(default=0)),
                ('pickupLon', models.FloatField(default=0)),
                ('pickupTime', models.TimeField(default=datetime.time(16, 0))),
            ],
        ),
        migrations.RemoveField(
            model_name='thirdgender',
            name='pickupLat',
        ),
        migrations.RemoveField(
            model_name='thirdgender',
            name='pickupLon',
        ),
        migrations.RemoveField(
            model_name='thirdgender',
            name='pickupTime',
        ),
        migrations.AddField(
            model_name='pwd',
            name='point',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pls.pickupPoint'),
        ),
        migrations.AddField(
            model_name='thirdgender',
            name='point',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pls.pickupPoint'),
        ),
    ]
