# Generated by Django 2.2 on 2019-04-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pls', '0005_auto_20190413_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pwd',
            name='pickupLat',
        ),
        migrations.RemoveField(
            model_name='pwd',
            name='pickupLon',
        ),
        migrations.RemoveField(
            model_name='pwd',
            name='pickupTime',
        ),
    ]
