# Generated by Django 2.2 on 2019-04-13 12:16

from django.db import migrations, models
import pls.models


class Migration(migrations.Migration):

    dependencies = [
        ('pls', '0006_auto_20190413_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pickuppoint',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=pls.models.picture_path),
        ),
    ]
