# Generated by Django 2.2 on 2019-04-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pls', '0007_auto_20190413_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
