# Generated by Django 2.2 on 2019-04-13 13:57

from django.db import migrations, models
import pls.models


class Migration(migrations.Migration):

    dependencies = [
        ('pls', '0008_candidate_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingstation',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=pls.models.user_path, validators=[pls.models.file_size]),
        ),
    ]
