# Generated by Django 2.2 on 2019-04-13 14:00

from django.db import migrations, models
import pls.models


class Migration(migrations.Migration):

    dependencies = [
        ('pls', '0009_auto_20190413_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=pls.models.can_path, validators=[pls.models.file_size]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='symbol',
            field=models.ImageField(blank=True, null=True, upload_to=pls.models.party_path, validators=[pls.models.file_size]),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=pls.models.picture_path, validators=[pls.models.file_size]),
        ),
    ]
